FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["./amorphie.transaction.hub/amorphie.transaction.hub.csproj", "."]
RUN dotnet restore "./amorphie.transaction.hub.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "./amorphie.transaction.hub/amorphie.transaction.hub.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "./amorphie.transaction.hub/amorphie.transaction.hub.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
EXPOSE 5002
ENV ASPNETCORE_URLS=http://+:5002
ENTRYPOINT ["dotnet", "amorphie.transaction.hub.dll"]