FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app

RUN adduser -u 5679 --disabled-password --gecos "" amorphie-transactionuser && chown -R amorphie-transactionuser:amorphie-transactionuser /app
USER amorphie-transactionuser

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["./amorphie.transaction.hub/amorphie.transaction.hub.csproj", "."]
RUN dotnet restore "./amorphie.transaction.hub.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "./amorphie.transaction.hub/amorphie.transaction.hub.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "./amorphie.transaction.hub/amorphie.transaction.hub.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
EXPOSE 5000
ENV ASPNETCORE_URLS=http://+:5000
ENTRYPOINT ["dotnet", "amorphie.transaction.hub.dll"]