apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: transaction-secretstore
spec:
  type: secretstores.hashicorp.vault
  version: v1
  metadata:
  - name: vaultAddr
    value: http://localhost:8200
  - name: vaultToken
    value: "hvs.J7XgfaTrAfKgLMELJQQ55ZFf"
  - name: skipVerify
    value: true
  - name: vaultKVUsePrefix
    value: false
  - name: enginePath
    value: "kv"